package gotemplate

const (
	NodeTypeIdentifier               = "identifier"
	NodeTypeVariable                 = "variable"
	NodeTypeDot                      = "dot"
	NodeTypeDollar                   = "$"
	NodeTypeDotSymbol                = "."
	NodeTypeVariableDefinition       = "variable_definition"
	NodeTypeRangeVariableDefinition  = "range_variable_definition"
	NodeTypeFieldIdentifier          = "field_identifier"
	NodeTypeText                     = "text"
	NodeTypeTemplate                 = "template"
	NodeTypeIfAction                 = "if_action"
	NodeTypeIf                       = "if"
	NodeTypeBlockAction              = "block_action"
	NodeTypeWithAction               = "with_action"
	NodeTypeRangeAction              = "range_action"
	NodeTypeDefineAction             = "define_action"
	NodeTypeFunctionCall             = "function_call"
	NodeTypeComment                  = "comment"
	NodeTypeSelectorExpression       = "selector_expression"
	NodeTypeElse                     = "else"
	NodeTypeElseIf                   = "else if"
	NodeTypeRange                    = "range"
	NodeTypeWith                     = "with"
	NodeTypeDefine                   = "define"
	NodeTypeOpenBraces               = "{{"
	NodeTypeOpenBracesDash           = "{{-"
	NodeTypeCloseBraces              = "}}"
	NodeTypeCloseBracesDash          = "-}}"
	NodeTypeEnd                      = "end"
	NodeTypeInterpretedStringLiteral = "interpreted_string_literal"
	NodeTypeBlock                    = "block"
	NodeTypeChainedPipeline          = "chained_pipeline"

	FieldNameAlternative = "alternative"
	FieldNameCondition   = "condition"
	FieldNameOption      = "option"
	FieldNameFunction    = "function"
)
